//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alfa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public int UserType { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int ID_Employee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual UserTypes UserTypes { get; set; }
    }
}
